import {
  Award,
  BatteryCharging,
  Briefcase,
  Building2,
  Calendar,
  Car,
  ChartColumn,
  Check,
  ClipboardCheck,
  Coins,
  Cpu,
  Factory,
  FileText,
  Fuel,
  Gauge,
  Handshake,
  HardHat,
  Headset,
  Hotel,
  House,
  Leaf,
  MapPin,
  Milestone,
  Monitor,
  Network,
  Plug,
  Route,
  Search,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  SquareParking,
  Store,
  Sun,
  Tractor,
  TrendingUp,
  Truck,
  Users,
  Wrench,
  Zap,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";
import type { IconName } from "@/types";

/**
 * Mapeia nomes semânticos (usados nos arquivos de dados) para ícones Lucide.
 * Mantém os dados desacoplados da biblioteca de ícones.
 */
const ICONS: Record<IconName, LucideIcon> = {
  sun: Sun,
  zap: Zap,
  plug: Plug,
  car: Car,
  home: House,
  building: Building2,
  factory: Factory,
  tractor: Tractor,
  store: Store,
  hotel: Hotel,
  parking: SquareParking,
  fuel: Fuel,
  cart: ShoppingCart,
  truck: Truck,
  leaf: Leaf,
  chart: ChartColumn,
  shield: ShieldCheck,
  wrench: Wrench,
  gauge: Gauge,
  battery: BatteryCharging,
  users: Users,
  route: Route,
  briefcase: Briefcase,
  clipboard: ClipboardCheck,
  cpu: Cpu,
  settings: Settings,
  handshake: Handshake,
  trending: TrendingUp,
  map: MapPin,
  monitor: Monitor,
  headset: Headset,
  calendar: Calendar,
  award: Award,
  search: Search,
  file: FileText,
  hardhat: HardHat,
  check: Check,
  coins: Coins,
  smartphone: Smartphone,
  network: Network,
  highway: Milestone,
};

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = ICONS[name];
  return <Component aria-hidden="true" {...props} />;
}
